config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'blog/articles#index', as: :home

  namespace :authors do
  	resources :articles
  end

  scope module: 'blog' do
	get 'about' => 'pages#about', as: :about
	get 'articles' => 'articles#index', as: :articles
	get 'articles/:id' => 'articles#show', as: :article
  end

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates_presence_of :title, :body #length: {minimum: 5}
	validates :title, length: {minimum: 5}


	belongs_to :author

end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :article
end

app/models/comment.rb
class Comment < ApplicationRecord
	acts_as_tree order: 'created_at DESC'

	def to_digraph_label
	  title
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/articles_controller.rb
module Authors
	class ArticlesController < AuthorController

		def index
			@articles = current_author.article.all # sort acc to timestamp later
		end

		def show
			@article = current_author.article.find(params[:id])
		end

		def new
			@article = current_author.article.new
		end

		def edit
			@article = current_author.article.find(params[:id])
		end

		def create
			#render plain: params[:post].inspect
			@article = current_author.article.new(article_params)

			if(@article.save)
				redirect_to authors_articles_path
			else
				render 'new'
			end
		end

		def update	
			@article = current_author.article.find(params[:id])

			if(@article.update(article_params))
				redirect_to @article
			else
				render "edit"
			end
		end

		def destroy
			@article = current_author.article.find(params[:id])
			@article.destroy

			redirect_to author_articles_path
		end



		private def article_params
			params.require(:post).permit(:title, :body)
		end
		
	end

end

app/controllers/blog/articles_controller.rb
module Blog
	class ArticlesController < BlogController

		def index
			@articles = Article.all # sort acc to timestamp later
		end

		def show
			@article = Article.find(params[:id])
		end
		
	end

end

app/controllers/blog/pages_controller.rb
module Blog
	class PagesController < BlogController

		def about
	
		end

	end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.hash_tree
  end

  def new
  	@comment = Comment.new(parent_id: params[:parent_id])
  end

  def create
  	if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to comments_path
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/articles/edit.html.erb
<%= form_for :post, url: authors_article_path(@article), method: :patch do |f| %>
	<% if @article.errors.any? %>
		<% @article.errors.full_messages.each do |err| %>
			<div class="alert alert-danger"> <%= err %> </div>
		<% end %>
	<% end %>


	<div class="row">
	    <div class="col-md-3">

			<div class="card" >
			  <div class="card-block">
			    <h4 class="card-title">Edit Article</h4>
			  </div>
			  <ul class="list-group list-group-flush">
			    <li class="list-group-item">
			    	<div class="field">
					    <%= f.label :title %><br>
					    <%= f.text_field :title, class: 'form-control' %>
				    </div>
			    </li>
			    <li class="list-group-item">
			    	<div class="actions">
					   <%= f.submit "Save Article", class: 'btn btn-success btn-block btn-lg'  %>
				  	</div>
			    </li>
			    <!-- <li class="list-group-item">
			    	
			    </li> -->
			  </ul>
			  
			</div>

	      
	     </div>

	     <div class="col-md-9">
	      <div class="field">
	        <%= f.label :body %>
	        <%= f.text_area :body, class: 'form-control' %>
	      </div>
	    </div>
	</div>

	

	
<% end %>



app/views/authors/articles/index.html.erb

<%= link_to "New Article",  new_authors_article_path, class: 'btn btn-md btn-info' %>
<br/><br/>

<h1> My Articles </h1>
<br/>



<div class="row">
	<table class="table table-striped">
		<tr>
			<th colspan="4">Title</th>
		</tr>
		<% @articles.each do |article| %>
		<tr>
			<td>
				<%= article.title %>
			</td>
			<td>
				<%= link_to "Read More",  authors_article_path(article), class: 'btn btn-sm btn-primary' %>
			</td>
			<td>
				<%= link_to "Edit",  edit_authors_article_path(article), class: 'btn btn-sm btn-warning' %>
			</td>
			<td>
				<%= link_to "Delete",  authors_article_path(article), method: :delete,
									data: {confirm: 'Are you sure want to delete?'},
									class: 'btn btn-sm btn-danger' %>

			</td>
		</tr>
		<% end %>

	</table>
</div>


app/views/authors/articles/new.html.erb
<h1> Create new post </h1>

<%= form_for :post, url: authors_articles_path do |f| %>
	<% if @article.errors.any? %>
		<% @article.errors.full_messages.each do |err| %>
			<div class="alert alert-danger"> <%= err %> </div>
		<% end %>
	<% end %>
	<p>
		<%= f.label :title %> <br>
	    <%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %> <br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>

<% end %>


app/views/authors/articles/show.html.erb
<%= link_to "Edit", edit_authors_article_path(@article), class: 'btn btn-sm btn-warning' %>
<%= link_to "Delete", authors_article_path(@article),
					method: :delete,
					data: {confirm: 'Are you sure want to delete?'},
					class: 'btn btn-sm btn-danger' %>

<div class="row">
	<div class="col-md-12 " style="text-align: center;">
<h1><%= @article.title %></h1>
<p><%= @article.body.html_safe %></p>
</div>
</div>


app/views/blog/articles/index.html.erb
<h1> All Articles </h1>
<div class="row">


	<% @articles.each do |article| %>
	<div class='col-sm-3 col-md-4' style="margin-bottom: 15px;">
		<div class="card">
		  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
		  <div class="card-body">
		  	
		  <div class="card-block">
		    <h4 class="card-title">
		    	<%= article.title %>
		    </h4>
		    <p class="card-text">
		    	<%= truncate(article.body, length: 130) %>
		    </p>
		    <%= link_to "Read More", article_path(article), class: 'btn btn-sm btn-primary' %>
		  </div>

		  </div>
		</div>
	</div>
	<% end %>

</div>

app/views/blog/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body.html_safe %></p>

<!-- Comment goes here -->

app/views/blog/pages/about.html.erb
<h1>About</h1>

app/views/comments/_comment.html.erb
<div class="well">
  <div>
    <span><strong><%= comment.title %></strong></span>
    <span><%= comment.body %></span>
    <span><%= comment.root? ? "Started by" : "Replied by" %> <strong><%= comment.author %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></span>
  </div>

  
  <% from_reply_form ||= nil %>
	<% unless from_reply_form %>
		<% if comment.leaf? %>
		 <small class="text-muted">There are no replies yet - be the first one to reply!</small>
  		<% end %>
		<p><%= link_to 'reply', new_comment_path(comment.id) %></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h3>Click the button below to start a new thread:</h3>
    <p>
      <%= link_to 'Add new comment', new_comment_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<%= comments_tree_for @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        	<li class="nav-item active">
        		<%= link_to "Home", home_path, class: "nav-link" %>
        	</li>
        	<li class="nav-item">
        		<%= link_to "Create New Post", new_authors_article_path, class: "nav-link" %>
        		<span class="sr-only">(current)</span></a>
        	</li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
            <span class="sr-only">(current)</span></a>
          </li>

          <% if author_signed_in? %>

          <li class="nav-item">
            <%= link_to "My Articles", authors_articles_path, class: "nav-link" %>
            <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <%= link_to "LogOut", destroy_author_session_path, method: :delete, class: "nav-link" %>
            <span class="sr-only">(current)</span></a>
          </li>

          <% end %>
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li> -->
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->
        </ul>
        
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>McZin</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script><!-- 
    <script>tinymce.init({ selector:'textarea' });</script> -->
  </head>

  <body>
	
  <%= render 'layouts/navbar' %>
    <div class="container" style="text-align: center">

    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    </div>

  </body>
</html>